version: 2.1
jobs:
  build-and-test:
    docker:
        - image: mariuscristian/numerous-requirements:1.0.0

    steps:
      - checkout
      - run:
          name: Tests
          command: |
            cp . numerous
            python3 -m numerous/pytest
